### ISSUE TITLE
fix SoluteIO validator

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#120]
In SoluteIO.js:

```js
//TODO #120 should be instanceof Solute, but require(Solute) is cyclic, and phet.phScale.Solute doesn't exist yet
SoluteIO.validator = { isValidValue: value => value instanceof Object };
```

This can presumably be addressed now that we are using ES6 modules, where cyclic dependencies are not an issue.

**Comment by pixelzoom** [comment]
I tried importing `Solute` in `SoluteIO`, like this:

```js
13 import Solute from './Solute.js';
47 SoluteIO.validator = { isValidValue: value => value instanceof Solute };
```

It fails `grunt update` with:

```
% grunt update
Running "update" task

Running "generate-development-html" task

Running "generate-phet-io-api-files" task
Fatal error: Perennial task failed: Error: ReferenceError: SoluteIO is not defined
    at new Solute (http://localhost/~cmalley/GitHub/ph-scale/js/common/model/Solute.js:62:19)
    at http://localhost/~cmalley/GitHub/ph-scale/js/common/model/Solute.js:139:24
%
```

I'm guessing that this is because I'm creating a static instance of `Solute` at line 139.

**Comment by pixelzoom** [comment]
I'll need to do what I did in phetsims/beers-law-lab#246.  That is, move static instances to their own .js file.

**Comment by pixelzoom** [comment]
Done in the above commit. Closing.
