### ISSUE TITLE
CT: full api expected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#216]
This is occurring occasionally in CT:

```
ph-scale : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (ph-scale, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4917ms
>> Production minification complete: 30857ms (1768322 bytes)
>> Debug minification complete: 1ms (5890757 bytes)
Building brand: phet-io
>> Webpack build complete: 3873ms
>> Production minification complete: 25869ms (1799098 bytes)
>> Debug minification complete: 24026ms (2067152 bytes)
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: full api expected
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1619002307084/chipper/js/grunt/copySupplementalPhetioFiles.js:294:5)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1619002307084/chipper/js/grunt/buildRunnable.js:355:5)
at /data/share/phet/continuous-testing/ct-snapshots/1619002307084/chipper/js/grunt/Gruntfile.js:255:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1619002307084/chipper/js/grunt/Gruntfile.js:74:7)

Full Error details:
AssertionError [ERR_ASSERTION]: full api expected

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error [Error: Timeout in generatePhetioMacroAPI
at Timeout._onTimeout (/data/share/phet/continuous-testing/ct-snapshots/1619002307084/chipper/js/phet-io/generatePhetioMacroAPI.js:87:46)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
]
Snapshot from 4/21/2021, 4:51:47 AM
```

**Comment by pixelzoom** [comment]
I tried to reproduce this locally using `grunt build --brands=phet,phet-io`, but it succeeds without error. 

I guess I'll have to dive into CT to see what the "build" test is actually running.

**Comment by pixelzoom** [comment]
According to @jonathanolson, CT runs `grunt --brands=phet,phet-io --lint=false`.   I tried that locally, and still could not reproduce.

@zepumph @samreid This is obviously related to PhET-iO.  What does "full API expected" mean? (Consider a more informative message.)  Why does this occur sporadically in CT?

**Comment by pixelzoom** [comment]
This is caused by puppeteer failing, and not being able to create the API for the running sim.  This will be investigated in chipper, and a better error message will be added in the meantime. See   https://github.com/phetsims/chipper/issues/1022 and https://github.com/phetsims/chipper/issues/1032.
