### ISSUE TITLE
CT MigrationReport problem: initialStatesAreIncompatible 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#293]
Also in basics:
```
ph-scale : migration : 1.6->main : assert
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/phet-io-wrappers/migration/?sim=ph-scale&oldVersion=1.6&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725773979093%7D
ERROR: Assertion failed: MigrationReport problem: initialStatesAreIncompatible 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [
    {
      "phetioID": "phScale.general.controller.input",
      "migratedInitialState": {
        "pointers": []
      },
      "newInitialState": {
        "pointers": [
          {
            "point": {
              "x": 0,
              "y": 0
            },
            "type": "pdom"
          }
        ]
      }
    }
  ],
  "propertyValidValueNoLongerSupported": [],
  "switchedFromInvalidValueToNewDefault": [],
  "phetioIDNotInNewAPI": [],
  "notStatefulAnymore": [],
  "incompletePhetioElementRenames": [],
  "incompletePhetioElementDeletes": [],
  "processedNothing": [],
  "newNeededIOTypes": {},
  "relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
  "missingStringPhetioElements": []
}
 [object Object]
STACK: Error: Assertion failed: MigrationReport problem: initialStatesAreIncompatible 
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/assert/js/assert.js:45:13)
    at assert (MigrationReport.ts:168:22)
    at reportForContext (MigrationEngine.ts:86:22)
    at migrate (StandardPhetioWrapper.ts:281:37)
    at async (http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/phet-io-wrappers/migration/migration.js:227:11)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1725773550845%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dph-scale%26oldVersion%3D1.6%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725773979093%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1725773550845%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dph-scale%26oldVersion%3D1.6%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725773979093%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/phet-io-wrappers/migration/?sim=ph-scale&oldVersion=1.6&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725773979093%7D
[ATTACHED] 
[NAVIGATED] about:blank
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/studio/?sim=ph-scale&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725773979093%7D&phetioMigrationReport=assert&fuzz&locales=*
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/ph-scale/ph-scale_en.html?brand=phet-io&ea&postMessageOnError&sim=ph-scale&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725773979093%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/ph-scale/1.6/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725773979093%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/ph-scale/1.6/ph-scale_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725773979093%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  MigrationReport problem: initialStatesAreIncompatible 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [
    {
      "phetioID": "phScale.general.controller.input",
      "migratedInitialState": {
        "pointers": []
      },
      "newInitialState": {
        "pointers": [
          {
            "point": {
              "x": 0,
              "y": 0
            },
            "type": "pdom"
          }
        ]
      }
    }
  ],
  "propertyValidValueNoLongerSupported": [],
  "switchedFromInvalidValueToNewDefault": [],
  "phetioIDNotInNewAPI": [],
  "notStatefulAnymore": [],
  "incompletePhetioElementRenames": [],
  "incompletePhetioElementDeletes": [],
  "processedNothing": [],
  "newNeededIOTypes": {},
  "relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
  "missingStringPhetioElements": []
} JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: MigrationReport problem: initialStatesAreIncompatible 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [
    {
      "phetioID": "phScale.general.controller.input",
      "migratedInitialState": {
        "pointers": []
      },
      "newInitialState": {
        "pointers": [
          {
            "point": {
              "x": 0,
              "y": 0
            },
            "type": "pdom"
          }
        ]
      }
    }
  ],
  "propertyValidValueNoLongerSupported": [],
  "switchedFromInvalidValueToNewDefault": [],
  "phetioIDNotInNewAPI": [],
  "notStatefulAnymore": [],
  "incompletePhetioElementRenames": [],
  "incompletePhetioElementDeletes": [],
  "processedNothing": [],
  "newNeededIOTypes": {},
  "relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
  "missingStringPhetioElements": []
}
 [object Object]
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/assert/js/assert.js:45:13)
    at MigrationReport.reportForContext (http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationReport.js:145:23)
    at MigrationEngine.migrate (http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationEngine.js:65:23)
    at StandardPhetioWrapper.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/chipper/dist/js/phet-io-wrappers/common/js/StandardPhetioWrapper.js:199:38)
    at async http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/phet-io-wrappers/migration/migration.js:227:11
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 9/7/2024, 11:32:30 PM

----------------------------------

ph-scale : migration : 1.6->main : assert
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/phet-io-wrappers/migration/?sim=ph-scale&oldVersion=1.6&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725776865620%7D
ERROR: Assertion failed: MigrationReport problem: initialStatesAreIncompatible 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [
    {
      "phetioID": "phScale.general.controller.input",
      "migratedInitialState": {
        "pointers": []
      },
      "newInitialState": {
        "pointers": [
          {
            "point": {
              "x": 0,
              "y": 0
            },
            "type": "pdom"
          }
        ]
      }
    }
  ],
  "propertyValidValueNoLongerSupported": [],
  "switchedFromInvalidValueToNewDefault": [],
  "phetioIDNotInNewAPI": [],
  "notStatefulAnymore": [],
  "incompletePhetioElementRenames": [],
  "incompletePhetioElementDeletes": [],
  "processedNothing": [],
  "newNeededIOTypes": {},
  "relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
  "missingStringPhetioElements": []
}
 [object Object]
STACK: Error: Assertion failed: MigrationReport problem: initialStatesAreIncompatible 
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/assert/js/assert.js:45:13)
    at assert (MigrationReport.ts:168:22)
    at reportForContext (MigrationEngine.ts:86:22)
    at migrate (StandardPhetioWrapper.ts:281:37)
    at async (http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/phet-io-wrappers/migration/migration.js:227:11)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1725773550845%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dph-scale%26oldVersion%3D1.6%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725776865620%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1725773550845%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dph-scale%26oldVersion%3D1.6%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725776865620%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/phet-io-wrappers/migration/?sim=ph-scale&oldVersion=1.6&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725776865620%7D
[ATTACHED] 
[NAVIGATED] about:blank
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/studio/?sim=ph-scale&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725776865620%7D&phetioMigrationReport=assert&fuzz&locales=*
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1725773550845/ph-scale/ph-scale_en.html?brand=phet-io&ea&postMessageOnError&sim=ph-scale&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725776865620%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/ph-scale/1.6/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725776865620%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/ph-scale/1.6/ph-scale_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale%22%2C%22migration%22%2C%221.6-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1725773550845%22%2C%22timestamp%22%3A1725776865620%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  MigrationReport problem: initialStatesAreIncompatible 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [
    {
      "phetioID": "phScale.general.controller.input",
      "migratedInitialState": {
        "pointers": []
      },
      "newInitialState": {
        "pointers": [
          {
            "point": {
              "x": 0,
              "y": 0
            },
            "type": "pdom"
          }
        ]
      }
    }
  ],
  "propertyValidValueNoLongerSupported": [],
  "switchedFromInvalidValueToNewDefault": [],
  "phetioIDNotInNewAPI": [],
  "notStatefulAnymore": [],
  "incompletePhetioElementRenames": [],
  "incompletePhetioElementDeletes": [],
  "processedNothing": [],
  "newNeededIOTypes": {},
  "relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
  "missingStringPhetioElements": []
} JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: MigrationReport problem: initialStatesAreIncompatible 

 {
  "stateSchemaIncompatible": [],
  "initialStatesAreIncompatible": [
    {
      "phetioID": "phScale.general.controller.input",
      "migratedInitialState": {
        "pointers": []
      },
      "newInitialState": {
        "pointers": [
          {
            "point": {
              "x": 0,
              "y": 0
            },
            "type": "pdom"
          }
        ]
      }
    }
  ],
```

**Comment by samreid** [comment]
I pushed a proposed fix following the established pattern from https://github.com/phetsims/density/issues/188. @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
👍🏻
